version: 2
jobs:
  build-stage:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: echo without prod context
          command: "echo \"non secret: [$NON_SECRET] secret: [$SECRET]\""
  build-prod:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: echo with prod context
          command: "echo \"non secret: [$NON_SECRET] secret: [$SECRET]\""
workflows:
  version: 2
  my-workflow:
    jobs:
      - build-stage
      - build-prod:
          context: prod
